Bom
Chris00/ocaml-csv pull request #37
Opened 2022-06-16 18:25 UTC by Chimrod

Here is a pull request for the issue #36.

The request allow to ignore the first bytes in the files if they match a know BOM pattern (actually UTF-8 and UTF-16 are checked). Without this check, thoses bytes are considered as a part of the first row.

The check is done in a pure function `check_bom`, which return the number of bytes to ignore. If we want to going further, we could also return the associated encoding in order to inform the caller of the file encoding (not implemented here). I’ve plugged the call in the function `fill_in_buf_or_Eof` which is where the data are read and stored.

I’ve added a test which fails without the code (see the issue for that).

2022-08-11 14:30 UTC, Chimrod commented
Hello, do you have any update on this pull request ?

2022-08-15 22:13 UTC, Chris00 requested changes

2022-08-15 22:13 UTC, Chris00 commented on src/csv.pp.ml
> +         List.fold_left (fun matched bom ->
Since you want to bail out as soon as you found a match, `find_map` seems more appropriate.

2022-08-15 22:13 UTC, Chris00 commented on src/csv.pp.ml
> +               let idx = ref (ic.in0) in
Braces are unnecessary.

2022-08-15 22:13 UTC, Chris00 commented on src/csv.pp.ml
> +                     let res = Char.equal c (Bytes.get ic.in_buf !idx) in
Wouldn't
```ocaml
let b = Bytes.get ic.in_buf !idx in
incr idx;
Char.equal b c
```
be clearer?

2022-08-16 09:36 UTC, Chimrod commented
Hi ! Thanks for your review and feedback. I will check all the points and answer them quickly.

2023-10-07 17:52 UTC, SGrondin commented
@Chimrod I've rebased your commits and finished the PR in #41 

Thank you for your contribution!

2023-10-07 17:52 UTC, closed without merging